// build.js — writes _site/, the copy of the app that GitHub Pages serves once
// its source is set to "GitHub Actions" (see .github/workflows/pages.yml).
//
// The only difference from the source is that the JSX is compiled here, once,
// instead of by Babel in the browser on every open. That skips a 3 MB download
// on first visit and several seconds of compiling on a phone. The five page
// scripts become one app.js, index.html loads it instead of Babel + the
// sources, and sw.js precaches the new file list. Everything else is copied
// as-is, including sync/, which the email automation publishes into.
//
// Run: npm run build. Opening index.html from a local server still works
// without building — it compiles in the browser as before.
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const Babel = require('@babel/standalone');

const ROOT = __dirname;
const OUT = path.join(ROOT, '_site');

// Page scripts in the order index.html loads them. Each one is wrapped in its
// own function in the bundle: routines.jsx and app.jsx both declare
// KIND_ICON, entryKind and Icon at top level, which only worked as separate
// scripts because Babel turned const into var.
const PAGE_SCRIPTS = ['notify-core.js', 'notify.js', 'sync-report.js', 'routines.jsx', 'app.jsx'];
const BUNDLE = 'app.js';

// Development-only files that are not deployed.
const SKIP = new Set(['.git', '.github', '.gitignore', 'node_modules', '_site', 'build.js',
  'package.json', 'package-lock.json', 'README.md']);
const skip = (name) => SKIP.has(name) || /\.test\.js$/.test(name);

// Same presets as Babel in the browser (react + env), with modern targets so
// async functions, classes and spread stay native instead of ES5 rewrites.
const BABEL_OPTIONS = {
  presets: [
    ['env', { targets: { chrome: '80', edge: '80', firefox: '78', safari: '14', ios: '14', samsung: '13' }, bugfixes: true }],
    'react',
  ],
  comments: false,
  compact: true,
};

function fail(msg) {
  console.error('build failed: ' + msg);
  process.exit(1);
}

function read(file) {
  return fs.readFileSync(path.join(ROOT, file), 'utf8');
}

function copyTree(from, to) {
  for (const name of fs.readdirSync(from)) {
    if (skip(name)) continue;
    const src = path.join(from, name);
    const dst = path.join(to, name);
    if (fs.statSync(src).isDirectory()) {
      fs.mkdirSync(dst, { recursive: true });
      copyTree(src, dst);
    } else {
      fs.copyFileSync(src, dst);
    }
  }
}

// ── 1. Bundle the page scripts ──
const parts = PAGE_SCRIPTS.map((file) => {
  let code = read(file);
  if (file.endsWith('.jsx')) {
    try {
      code = Babel.transform(code, Object.assign({ filename: file }, BABEL_OPTIONS)).code;
    } catch (e) {
      fail(file + ' does not compile: ' + e.message);
    }
  }
  return '// ' + file + '\n;(function () {\n' + code + '\n})();\n';
});
const bundle = '/* Built by build.js from ' + PAGE_SCRIPTS.join(', ') + '. Edit those files, not this one. */\n' + parts.join('');
try { new vm.Script(bundle, { filename: BUNDLE }); } catch (e) { fail('the bundle does not parse: ' + e.message); }

// ── 2. index.html: one script instead of Babel + five sources ──
let html = read('index.html');
const babelTag = /[ \t]*<script[^>]*@babel\/standalone[^>]*><\/script>\n?/;
if (!babelTag.test(html)) fail('index.html has no Babel script tag to remove');
html = html.replace(babelTag, '');
PAGE_SCRIPTS.forEach((file, i) => {
  const tag = new RegExp('[ \\t]*<script[^>]*\\ssrc="' + file.replace(/\./g, '\\.') + '"[^>]*><\\/script>\\n?');
  if (!tag.test(html)) fail('index.html does not load ' + file + ' — update PAGE_SCRIPTS in build.js');
  html = html.replace(tag, i === 0 ? '<script src="' + BUNDLE + '"></script>\n' : '');
});
if (/\.jsx|text\/babel/.test(html)) fail('index.html still refers to JSX after rewriting');

// ── 3. sw.js: precache the built files ──
let sw = read('sw.js');
const block = /\/\/ @build-start\n([\s\S]*?)\/\/ @build-end\n/.exec(sw);
if (!block) fail('sw.js is missing its // @build-start … // @build-end block');
const cfg = {};
vm.runInNewContext(block[1] + ';this.CACHE = CACHE; this.APP_SHELL = APP_SHELL; this.VENDOR = VENDOR;', cfg);
const bundled = new Set(PAGE_SCRIPTS.filter(f => f !== 'notify-core.js' && f !== 'sync-report.js')); // the worker still imports those two
const shell = [];
cfg.APP_SHELL.forEach((u) => {
  const entry = bundled.has(u) ? BUNDLE : u;
  if (!shell.includes(entry)) shell.push(entry);
});
if (!shell.includes(BUNDLE)) shell.splice(shell.indexOf('styles.css') + 1, 0, BUNDLE);
const vendor = cfg.VENDOR.filter(u => !/@babel\/standalone/.test(u));
sw = sw.replace(block[0], '// @build-start (generated by build.js)\n' +
  'var CACHE = ' + JSON.stringify(cfg.CACHE + '-built') + ';\n' +
  'var APP_SHELL = ' + JSON.stringify(shell, null, 2) + ';\n' +
  'var VENDOR = ' + JSON.stringify(vendor, null, 2) + ';\n' +
  '// @build-end\n');

// ── 4. Write _site ──
fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT);
copyTree(ROOT, OUT);
fs.writeFileSync(path.join(OUT, BUNDLE), bundle);
fs.writeFileSync(path.join(OUT, 'index.html'), html);
fs.writeFileSync(path.join(OUT, 'sw.js'), sw);

// ── 5. Checks ──
// A missing precache file makes the service worker's install fail, which
// loses offline use and reminders; check every entry exists.
shell.forEach((u) => {
  if (u !== './' && !fs.existsSync(path.join(OUT, u))) fail('sw.js precaches ' + u + ' but _site has no such file');
});
// The sync slot must be deployed, or published water tests stop arriving.
const syncCtx = { self: {}, URL };
vm.runInNewContext(read('sync-report.js'), syncCtx);
const syncPath = syncCtx.self.PoolSync && syncCtx.self.PoolSync.PATH;
if (!syncPath || !fs.existsSync(path.join(OUT, syncPath))) fail('the sync file (' + syncPath + ') is missing from _site');

const kb = (n) => (n / 1024).toFixed(0) + ' KB';
console.log('built _site/: ' + BUNDLE + ' ' + kb(bundle.length) + ', ' + shell.length + ' precached files, sync file included');
